use axum::{http::header, response::IntoResponse, Json};
use utoipa::OpenApi;

use crate::routes::{
    auxiliary::{
        BroadcastRecord, BroadcastStatus, ContradictionRecord, ContradictionStatus,
        NarrativeRecord, NarrativeStatus,
    },
    broadcasts::{
        Broadcast, BroadcastDetailResponse, BroadcastError, BroadcastGenerateRequest,
        BroadcastLatestResponse, BroadcastsResponse,
    },
    claims::ClaimsResponse,
    config::{ConfigError, ConfigResponse},
    contradictions::{
        Contradiction, ContradictionDetailResponse, ContradictionError,
        ContradictionResolveRequest, ContradictionsResponse,
    },
    derived_events::{DerivedEventError, DerivedEventsQuery, DerivedEventsResponse},
    documents::DocumentsResponse,
    entities::{
        EntitiesResponse, EntityDetailResponse, EntityError, EntityMergeRequest,
        EntityMergeResponse, EntitySummary, EntitySummaryResponse,
    },
    events::{EventError, EventResolveRequest, EventResolveResponse, EventsResponse},
    export::{
        ExportResponse, ExtractedClaimSummary, ExtractedEntitySummary, ExtractedRelationshipSummary,
    },
    extractions::ExtractionsResponse,
    health::{HealthResponse, ServiceHealth},
    monitoring::MonitoringResponse,
    narratives::{Narrative, NarrativeDetailResponse, NarrativeError, NarrativesResponse},
    recovery::{RecoveryCheckResponse, RecoveryErrorBody, RecoveryResponse},
    search::{ClaimHit, DocumentHit, EntityHit, SearchResponse},
    sources::{
        SourceInfo, SourceRegistryEntryResponse, SourceRegistryError, SourceRegistryListResponse,
        SourceRegistryTriggerResponse, SourcesResponse,
    },
    stats::StatsResponse,
};

/// OpenAPI specification for the Objective API gateway.
///
/// Aggregates the in-place `#[utoipa::path]` annotations defined on every
/// route handler in this crate so a single JSON document can be served to
/// clients and external tooling.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "Objective API",
        version = "0.1.0",
        description = "Internal API for the local-first Objective intelligence platform.",
        contact(name = "Objective", url = "https://github.com/kliewerdaniel/objective05")
    ),
    paths(
        crate::routes::health::get_health,
        crate::routes::stats::get_stats,
        crate::routes::monitoring::get_metrics,
        crate::routes::documents::list_documents,
        crate::routes::extractions::list_extractions,
        crate::routes::events::list_events,
        crate::routes::events::resolve_event,
        crate::routes::derived_events::list_derived_events,
        crate::routes::derived_events::list_top_derived_events,
        crate::routes::entities::list_entities,
        crate::routes::entities::list_entity_summary,
        crate::routes::entities::merge_entities,
        crate::routes::claims::list_claims,
        crate::routes::sources::list_sources,
        crate::routes::sources::list_registered_sources,
        crate::routes::sources::create_source,
        crate::routes::sources::get_registered_source,
        crate::routes::sources::update_source,
        crate::routes::sources::delete_source,
        crate::routes::sources::trigger_source,
        crate::routes::narratives::list_narratives,
        crate::routes::narratives::get_narrative,
        crate::routes::broadcasts::list_broadcasts,
        crate::routes::broadcasts::latest_broadcast,
        crate::routes::broadcasts::get_broadcast,
        crate::routes::broadcasts::generate_broadcast,
        crate::routes::contradictions::list_contradictions,
        crate::routes::contradictions::get_contradiction,
        crate::routes::contradictions::resolve_contradiction,
        crate::routes::recovery::get_recovery_state,
        crate::routes::recovery::post_recovery_check,
        crate::routes::export::export_data,
        crate::routes::search::search,
        crate::routes::config::get_config,
    ),
    components(
        schemas(
            HealthResponse,
            ServiceHealth,
            StatsResponse,
            MonitoringResponse,
            objective_store::monitoring::PipelineMetrics,
            DocumentsResponse,
            ExtractionsResponse,
            EventsResponse,
            DerivedEventsQuery,
            DerivedEventsResponse,
            DerivedEventError,
            EntitiesResponse,
            EntitySummary,
            EntitySummaryResponse,
            ClaimsResponse,
            SourcesResponse,
            SourceInfo,
            SourceRegistryListResponse,
            SourceRegistryEntryResponse,
            SourceRegistryError,
            SourceRegistryTriggerResponse,
            objective_ingestion::SourceDefinition,
            objective_ingestion::SourceType,
            objective_ingestion::SourcePatch,
            NarrativesResponse,
            Narrative,
            NarrativeDetailResponse,
            NarrativeError,
            NarrativeRecord,
            NarrativeStatus,
            BroadcastsResponse,
            Broadcast,
            BroadcastDetailResponse,
            BroadcastLatestResponse,
            BroadcastError,
            BroadcastGenerateRequest,
            BroadcastRecord,
            BroadcastStatus,
            ContradictionsResponse,
            Contradiction,
            ContradictionDetailResponse,
            ContradictionError,
            ContradictionResolveRequest,
            ContradictionRecord,
            ContradictionStatus,
            EntityDetailResponse,
            EntityError,
            EntityMergeRequest,
            EntityMergeResponse,
            EventError,
            EventResolveRequest,
            EventResolveResponse,
            ExportResponse,
            ExtractedEntitySummary,
            ExtractedClaimSummary,
            ExtractedRelationshipSummary,
            SearchResponse,
            DocumentHit,
            EntityHit,
            ClaimHit,
            ConfigResponse,
            ConfigError,
            RecoveryResponse,
            RecoveryCheckResponse,
            RecoveryErrorBody,
            objective_store::recovery::RecoveryState,
            objective_store::recovery::RecoveryCheck,
            objective_store::recovery::RecoveryEvent,
            objective_store::recovery::ServiceStatus,
            objective_core::types::BodyFormat,
            objective_core::types::RawDocument,
            objective_core::types::EntityType,
            objective_core::types::ExtractedEntity,
            objective_core::types::ClaimType,
            objective_core::types::ExtractedClaim,
            objective_core::types::ExtractedRelationship,
            objective_core::types::ExtractionResult,
            objective_core::types::EventEnvelope,
            objective_core::types::EventMetadata,
            objective_core::types::Event,
            objective_core::types::EventStatus,
            objective_core::types::EventType,
        )
    ),
    tags(
        (name = "health", description = "Service health and uptime."),
        (name = "stats", description = "Aggregate system statistics."),
        (name = "monitoring", description = "Pipeline monitoring metrics and operational visibility."),
        (name = "documents", description = "Normalized documents ingested from sources."),
        (name = "extractions", description = "Entities, claims, and relationships extracted from documents."),
        (name = "events", description = "Internal event bus traffic."),
        (name = "derived-events", description = "Events produced by the correlation engine from extracted claims."),
        (name = "entities", description = "Entities aggregated across all extractions."),
        (name = "claims", description = "Claims extracted from documents."),
        (name = "sources", description = "Aggregated source statistics and on-demand source management."),
        (name = "source-registry", description = "Registered ingestion source registry CRUD and manual trigger."),
        (name = "narratives", description = "Aggregated story threads across claims and events."),
        (name = "broadcasts", description = "Generated reports and podcasts."),
        (name = "contradictions", description = "Contradicting claims detected between sources."),
        (name = "events", description = "Internal event bus traffic and event resolution actions."),
        (name = "export", description = "Bulk JSON export of the running dataset."),
        (name = "search", description = "Substring search across documents, entities, and claims."),
        (name = "config", description = "Active configuration of the running gateway."),
        (name = "recovery", description = "Pipeline health, crash detection, and recovery state."),
    )
)]
pub struct ApiDoc;

pub async fn get_openapi_spec() -> impl IntoResponse {
    let spec = ApiDoc::openapi();
    let body = Json(spec);
    ([(header::CONTENT_TYPE, "application/json")], body)
}
