[package]
name = "objective-ingestion"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
feed-rs.workspace = true
objective-core = { path = "../core" }
regex.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tracing.workspace = true
ulid.workspace = true

[dev-dependencies]
objective-message-bus = { path = "../message-bus" }
objective-store = { path = "../store" }
