[package]
name = "objective-store"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
flate2.workspace = true
objective-core = { path = "../core" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
ulid.workspace = true
utoipa.workspace = true

[dev-dependencies]
objective-message-bus = { path = "../message-bus" }
tempfile.workspace = true

